### PR TITLE
Fixes #537: finally block needs a null check on writer, writer will be null if initializations fails

### LINKED ISSUE #537: Null pointer exception while writing to a report
java.lang.NullPointerException
	at com.relevantcodes.extentreports.utils.Writer.write(Writer.java:28)
	at com.relevantcodes.extentreports.HTMLReporter.flush(HTMLReporter.java:186)
	at com.relevantcodes.extentreports.Report.flush(Report.java:464)
	at com.relevantcodes.extentreports.ExtentReports.flush(ExtentReports.java:903)

Scenario:
Parent child relationship.
After creation of the report, open the report file to see the current steps written,
When the program tries to write the test result, the above exception is occuring.

### PR DESCRIPTION
**Pull request by toolsqa**
If writer initialisation fails because of some reason, then finally block will try to close the writer and will get a null pointer.

### CODE REVIEW

File: java/extentreports/src/main/java/com/relevantcodes/extentreports/Report.java [hunk 1]
```diff
@@ -228,7 +228,7 @@
     
     protected SuiteTimeInfo suiteTimeInfo;
     protected SystemInfo systemInfo;
-    protected List<ExtentTest> testList;
+    protected List<ExtentTest> testList = new ArrayList<ExtentTest>();
```
Comment (toolsqa) [inline java/extentreports/src/main/java/com/relevantcodes/extentreports/Report.java]: This and the ExtentReports.java fix is #320 , Couldn't figure out if its the same null pointer or not. But if you think this is a new issue change the merge description.

I am not sure about the business requirements. If no tests are added do we really want to generate an empty report or not. In this fix I have just fixed the exception, business rules needs to be implemented separately.

**Comment by ranadinesh786** [comment]
issue :
=====
 How to solve NULLPOINTEREXCEPTION while using grouping concepts in POM with Extends Reporting ?


Solutions: 
======
	       1. Use below parameters to all the configuration annotations which we are using i.e. in base test;
		(alwaysRun = true)
		2. Use valid try catch block inside the page class and don’t use throws [incorrect exception]
		3. Use parameterized values instead of taking hardcode values inside the page or script.
